services:
  calculadora:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculadora-mercado
    restart: unless-stopped
    ports:
      - "3019:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - mercado-api

  mercado-api:
    build:
      context: ./mercado-api
    container_name: mercado-api
    restart: unless-stopped
    ports:
      - "3011:3011"
    volumes:
      - ./mercado-api/data:/app/data
